name: Deploy

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        env:
          NOTION_TOKEN: ${{ vars.NOTION_TOKEN }}
        run: make build

      - name: Build
        if: github.ref == 'refs/heads/main'
        run: make build
