name: Deploy

on:
  push:
  schedule:
    - cron: "5 * * * *"

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync
        env:
          NOTION_TOKEN: ${{ vars.NOTION_TOKEN }}
        run: make sync

      - name: Build
        run: make build

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: make deploy
        env:
          INPUT_REMOTE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
