name: Deploy

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        env:
          NOTION_TOKEN: ${{ vars.NOTION_TOKEN }}
        run: make build

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: Burnett01/rsync-deployments@7.0.1
        with:
          switches: -r --delete-after
          path: output/
          remote_path: /home1/eczrvsmy/public_html/website_287658e3/
          remote_host: 50.6.153.225
          remote_user: eczrvsmy
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
